#!/bin/sh

cfgfile="${XDG_CONFIG_HOME:-$HOME/.config}/s4k/config.h"
cfmfile="${XDG_CONFIG_HOME:-$HOME/.config}/s4k/config.mk"
frmfile="${XDG_CONFIG_HOME:-$HOME/.config}/s4k/formats_*.h"

if [ -f $cfgfile ]; then
	s4kbin="${XDG_DATA_HOME:-$HOME/.local/share}/s4k/s4k"
	if [ $cfgfile -nt $s4kbin -o ! -f $s4kbin ]; then
		makedir="/tmp/s4k$$"
		mkdir $makedir
		cp -R "S4KSRC"* $makedir
		cp -f $cfgfile $makedir
		cp -f $cfmfile $makedir
		cp -f $frmfile $makedir
		cd $makedir
		make
		R=$?
		if [ $R -gt 0 ] && [ $R -le 127 ]; then
			s4kbinb=`which s4k`
		else
			mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/s4k"
			cp s4k $s4kbin
		fi
		rm -Rf $makedir
	fi
else
	s4kbinb=`which s4k`
fi

exec $s4kbin >> ~/.local/share/s4k/log 2>&1
